modLoader="javafml"
loaderVersion="[46,)"
license="MIT"
showAsResourcePack=false

[[mods]]
  modId="jukeboxmutes"
  version="0.0.0"
  displayName="Jukebox Mutes Music"
  authors="MsDogGirl"
  description='''
  When a music disc plays, mutes the game music. Fixes music overlap issue.
  '''
  displayTest="MATCH_VERSION"

[[dependencies.jukeboxmutes]]
  modId="minecraft"
  mandatory=true
  versionRange="[1.20.1]"
  ordering="NONE"
  side="BOTH"